import { PublicPageShell, Section } from '../components/legal/PublicPageShell'

export const Privacy = () => (
  <PublicPageShell title="Privacy Policy" lastUpdated="September 24, 2026">
    <p>
      Kitch ("Kitch," "we," "our") is a fridge, freezer, and pantry inventory app. This page explains, in plain
      language, what information Kitch collects, why, and how you can control it. It describes what the app actually
      does — nothing more.
    </p>

    <Section heading="Information you provide">
      <p>When you create a Kitch account, we collect the email address and password you sign up with.</p>
      <p>
        As you use the app, the following is stored so Kitch can function and sync across your devices: your
        inventory items, shopping list, storage locations (e.g. fridge, freezer, pantry), custom categories, recipe
        preferences and avoided ingredients, notification and display settings, and a history of items you've added,
        consumed, or discarded (used to power the in-app Stats screen). None of this is required to include anything
        beyond what you choose to type or scan in.
      </p>
    </Section>

    <Section heading="Where this information is stored">
      <p>
        Kitch stores your account and app data using Supabase, our database and authentication provider. Supabase
        hosts the database, handles sign-in, and — under the hood — powers the "sync across your devices" feature:
        when you're signed in on more than one device, your data updates on all of them, because it lives in this
        one shared account database. Your data is never visible to other Kitch users.
      </p>
      <p>
        We don't run our own servers beyond this — Kitch has no separate backend infrastructure of its own outside
        of Supabase.
      </p>
    </Section>

    <Section heading="Barcode scanning and Open Food Facts">
      <p>
        When you scan a product barcode, Kitch sends the barcode number directly from your device to{' '}
        <a href="https://world.openfoodfacts.org" target="_blank" rel="noopener noreferrer" className="font-medium text-[var(--color-accent)]">
          Open Food Facts
        </a>
        , a free, independent, open product database, to look up the product's name, brand, and photo. This request
        goes straight from your device to Open Food Facts — it does not pass through or get stored on Kitch's own
        servers. Once a product is found, Kitch may keep a local cache of that lookup in your account (linked to the
        barcode) purely so re-scanning the same product later is instant. Open Food Facts is a separate service with
        its own data practices, which you can read about on their site.
      </p>
    </Section>

    <Section heading="Local notifications">
      <p>
        If you turn on expiry reminders, Kitch schedules notifications directly on your own device based on the
        expiration dates already stored in your inventory. These reminders are generated and delivered entirely on
        your device — on iOS, through Apple's local notification system, and on web, through your browser's
        notification permission. No notification content is sent through, or generated by, any external push
        notification service, and nothing about your reminders is shared with anyone.
      </p>
    </Section>

    <Section heading="Account emails">
      <p>
        Kitch sends a small number of transactional emails tied directly to your account — such as confirming your
        sign-up or helping you reset a forgotten password. These are sent from{' '}
        <span className="font-medium text-[var(--color-ink)]">noreply@kitchapp.no</span> via our email delivery
        provider, solely to deliver that specific email to you. We do not send marketing or promotional email, and
        your email address is never used for anything beyond authenticating you and delivering these account
        messages.
      </p>
    </Section>

    <Section heading="What Kitch does not do">
      <p>
        Kitch does not use analytics, advertising, or tracking software of any kind, and there is no crash-reporting
        or usage-analytics SDK built into the app. We do not sell your data, and we do not share it with third
        parties for marketing or advertising purposes. The only outside services Kitch talks to are the ones named
        above — Supabase (to run the app) and Open Food Facts (only when you scan a barcode) — and, for transactional
        account email only, our email delivery provider.
      </p>
    </Section>

    <Section heading="Your data, your control">
      <p>
        You can export a complete copy of your Kitch data at any time from Settings → Export — this downloads a JSON
        file containing everything listed above, directly to your device.
      </p>
      <p>
        You can delete your account at any time from Settings → Delete Account. This permanently and immediately
        deletes your account and every piece of data associated with it — inventory, shopping list, storage
        locations, categories, preferences, and settings — from Kitch's database. This action cannot be undone, and
        nothing is retained afterward.
      </p>
    </Section>

    <Section heading="Your rights (GDPR)">
      <p>
        If you're located in the EU, EEA, UK, or Norway, you have rights under GDPR over your personal data,
        including the right to access it (Export, above), correct it (edit it directly in the app at any time),
        erase it (Delete Account, above), and request a portable copy of it in a machine-readable format (the same
        Export feature provides this as JSON). If you have a question about your data that isn't covered by the
        in-app tools above, you can reach out using the contact details below.
      </p>
    </Section>

    <Section heading="Children">
      <p>Kitch is not directed at children, and we do not knowingly collect personal data from children.</p>
    </Section>

    <Section heading="Changes to this policy">
      <p>
        If how Kitch handles data changes, we'll update this page and revise the "Last updated" date above. We
        encourage checking back here occasionally, especially before any major app update.
      </p>
    </Section>

    <Section heading="Contact">
      <p>
        Questions about this policy or your data can be sent to{' '}
        <a href="mailto:support@kitchapp.no" className="font-medium text-[var(--color-accent)]">
          support@kitchapp.no
        </a>
        .
      </p>
    </Section>
  </PublicPageShell>
)
